### ISSUE TITLE
Stackrating shouldn't count deleted questions

### ISSUE THREAD

**Issue by dippas** [aioobe/stackrating#1]
So I stumbled up on your project, I found it interesting, but while I was testing a few of my answers, I saw the systems is still counting the deleted ones, 

If stackoverflow by itself doesn't count them, and only users with 10k rep can see them, I thought the system shouldn't count them as well.

**Comment by Comparific** [comment]
This is by design. If you would be able to revoke all answers that end up with a negative rating delta, you could game the system.

The current solution isn't perfect, but a) deleted answers aren't super common and the Elo system should be stable enough to withstand any (small) injustice caused by this, and b) I don't know of a better solution.

**Comment by aioobe** [comment]
This is by design. If you would be able to revoke all answers that end up with a negative rating delta, you could game the system.

The current solution isn't perfect, but a) deleted answers aren't super common and the Elo system should be stable enough to withstand any (small) injustice caused by this, and b) I don't know of a better solution.
